Cadsobs adaptor
ecmwf-projects/cads-adaptors pull request #70
Opened 2023-11-24 13:06 UTC by garciampred

2023-11-30 11:19 UTC, EddyCMWF requested changes
When the merge from main is done and the small change I requested is made I am happy to merge

2023-11-30 11:19 UTC, EddyCMWF commented on cads_adaptors/adaptors/cadsobs.py
> +        mapped_request = apply_mapping(request, self.mapping)
Could you merge from main and then change this to:
```suggestion
        self._pre_retrieve(request=request)
```

2023-11-30 11:22 UTC, EddyCMWF commented
Actually, there are quite a few references to mapped_request, can you update them to reference the class attribute, self.mapped_request

2023-11-30 11:48 UTC, garciampred commented
Like this? I just assigned mapped_request = self.mapped_request, which is what I usually do to avoid repeating self everywhere.

2023-12-01 11:49 UTC, EddyCMWF approved these changes

2023-12-01 11:49 UTC, merged

2023-12-01 11:50 UTC, EddyCMWF commented
Thanks @garciampred !